### ISSUE TITLE
Group slack?

### ISSUE THREAD

**Issue by eerison** [ThomasBerends/symfony-certification-preparation-list#2]
Hello guys!
I study too for certified symfony , I start studys today and want can talk with you!
you have some groups of conversation?

**Comment by DavidGarciaCat** [comment]
I am trying to study for the Symfony Certificate too, I think some groups could be very useful. If you don't have a group, what about Gitter?

**Comment by ThomasBerends** [comment]
Hey guys, I love this idea and was thinking of it earlier, but didn't think there would be demand. Guess I'm proven wrong! I'm gonna check a few options for this in the next couple of days.

Thanks for opening this issue. I'll update on this soon.

**Comment by eerison** [comment]
very good! :D 
@DavidGarciaCat and @ThomasBerends you use what of chat?
hangout?
slack?

I think slack cool :)

**Comment by DavidGarciaCat** [comment]
@eerison I use "too much" tools:
- Slack and Skype at work
- Hangouts, WhatsApp and Telegram with friends and family
- Gitter to discuss upcoming changes when contributing on Open-Source Software

Any of them is fine to me

**Comment by eerison** [comment]
@DavidGarciaCat very good!
I don't know Gitter!

I will sing up

**Comment by eerison** [comment]
I find this group https://gitter.im/certificationy/certificationy!
I think it's cool we join them, what do you guys think?

**Comment by ThomasBerends** [comment]
@eerison I will be making a Slack group that I'll manage. No need to do this yourself. I don't want this project to become a mess of different communities managed by a lot of people.

**Comment by ThomasBerends** [comment]
I've created a Slack group. You can get an invite here:
https://join.slack.com/t/symfonycertification/shared_invite/enQtMjUxNjM5NjMzMDE1LTE4M2VhMWQzODIyMTU5ODI2MjM5NDIwYzAxYTk5MTljY2UxNzBmZDQ1MmM4ZGJhYWNiNmNlOWMxMWI2MmVkYTc
