### ISSUE TITLE
Filling up the last empty topics

### ISSUE THREAD

**Issue by ThomasBerends** [ThomasBerends/symfony-certification-preparation-list#22]
Some topics currently still don't have links. I thought it would be handy to make a list of them so we can fill it up:

- [ ] Standardization - Third-party libraries integration
- [ ] Standardization - Framework overloading
- [x] Controllers - The base Controller class
- [ ] Controllers - The response
- [x] Controllers - The cookies
- [x] Data Validation - Violations builder
- [ ] Dependency Injection - Built-in services
- [ ] Dependency Injection - Semantic configuration
- [ ] Security - Users
- [ ] Security - Access Control Rules
- [ ] Console - Input and Output objects
- [ ] Automated Tests - Handling legacy deprecated code
- [ ] Miscellaneous - Web Profiler and Web Debug Toolbar

It is possible that some of these topics are not covered in the Symfony documentation at all, in that case we need to contact the team so we fill up those holes in the Symfony documentation first.

**Comment by Pierstoval** [comment]
Sorry I won't have doc links for all points, but here are some:

---

> * [ ]  Controllers - The base Controller class

* https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php
* https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php

---

> * [ ]  Controllers - The response
> * [ ]  Controllers - The cookies

* https://symfony.com/doc/current/components/http_foundation.html

---

> * [ ]  Data Validation - Violations builder

* https://symfony.com/doc/current/validation/custom_constraint.html

---

> * [ ]  Dependency Injection - Semantic configuration

* https://symfony.com/doc/current/components/config.html
* Case-specific for the definition: https://symfony.com/doc/current/components/config/definition.html

---

> * [ ]  Security - Users
> * [ ]  Security - Access Control Rules

* https://symfony.com/doc/current/security.html
* https://symfony.com/doc/current/security/user_provider.html
* https://symfony.com/doc/current/security.html#securing-url-patterns-access-control
* https://symfony.com/doc/current/security/access_control.html

---

> * [ ]  Console - Input and Output objects

* https://symfony.com/doc/current/console/input.html
* https://symfony.com/doc/current/console.html#console-output
* https://symfony.com/doc/current/console/coloring.html
* https://symfony.com/doc/current/components/console/helpers/formatterhelper.html

---

> * [ ]  Automated Tests - Handling legacy deprecated code

* https://symfony.com/doc/current/components/phpunit_bridge.html#mark-tests-as-legacy

---

> * [ ]  Miscellaneous - Web Profiler and Web Debug Toolbar

* https://symfony.com/doc/current/profiler.html
* https://symfony.com/doc/current/reference/configuration/web_profiler.html

**Comment by ThomasBerends** [comment]
Closing this since it's outdated and applies to an older version.
