### ISSUE TITLE
Takeover 

### ISSUE THREAD

**Issue by askeita** [ThomasBerends/symfony-certification-preparation-list#32]
Hello @ThomasBerends I would be pleased to take over this project, if you agree. 😃

**Comment by ThomasBerends** [comment]
Hey @askeita ! What I would prefer to make sure it falls into good hands is that you first contribute to the project. I still have enough time to check PR's.

**Comment by cosminsandu** [comment]
I'm also willing to help!

**Comment by cosminsandu** [comment]
Created pull request for Symfony 6.0 
https://github.com/ThomasBerends/symfony-certification-preparation-list/pull/39

**Comment by cosminsandu** [comment]
Check fork here: https://github.com/cosminsandu/symfony-certification-preparation-list

**Comment by ThomasBerends** [comment]
@cosminsandu Thanks for the amazing work :D

**Comment by ThomasBerends** [comment]
Hey all. In April I'm starting a new job and I'll be working full-time on Symfony projects again. I'm closing this issue since a takeover is no longer needed. I'll be able to keep the list up to date again :smile:

Of course, help is still appreciated.
